package ca.duldeb.sipcall;

import static org.junit.Assert.assertArrayEquals;

import org.junit.Test;

public class DtmfPayloadTest {

    public static byte[] hexStringToByteArray(String s) {
        int len = s.length();
        byte[] data = new byte[len / 2];
        for (int i = 0; i < len; i += 2) {
            data[i / 2] = (byte) ((Character.digit(s.charAt(i), 16) << 4)
                                 + Character.digit(s.charAt(i+1), 16));
        }
        return data;
    }
    
    @Test
    public void testTwo()
    {
        DtmfPayload payload = new DtmfPayload(true, '2', true, 320);
        byte[] data = payload.toBytes();
        byte[] expected = hexStringToByteArray("028a0140"); // From DTMF 2, end of event, volume 10, duration 320 as generated by PhonerLite
        assertArrayEquals(expected, data);
    }

    @Test
    public void testStar()
    {
        DtmfPayload payload = new DtmfPayload(true, '*', true, 640);
        byte[] data = payload.toBytes();
        byte[] expected = hexStringToByteArray("0a8a0280"); // From DTMF *, end of event, volume 10, duration 640 as generated by PhonerLite
        assertArrayEquals(expected, data);
    }
}
